/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DetailsRouteImport } from './routes/details'
import { Route as IndexRouteImport } from './routes/index'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsRoute = DetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/details': typeof DetailsRoute
  '/discover': typeof DiscoverRoute
  '/home': typeof HomeRoute
  '/watchlist': typeof WatchlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/details' | '/discover' | '/home' | '/watchlist'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/details' | '/discover' | '/home' | '/watchlist'
  id: '__root__' | '/' | '/details' | '/discover' | '/home' | '/watchlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailsRoute: typeof DetailsRoute
  DiscoverRoute: typeof DiscoverRoute
  HomeRoute: typeof HomeRoute
  WatchlistRoute: typeof WatchlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailsRoute: DetailsRoute,
  DiscoverRoute: DiscoverRoute,
  HomeRoute: HomeRoute,
  WatchlistRoute: WatchlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
